# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d56c60fff81506fcd44783eec66673b9cd7dbafd42ef80d446125c53158844d062b214e7f5c6bd91d36933709efd5cbb6a581036c037c162a5b2879b16c818f7

test:
  secret_key_base: 4070c95f2ab4f0e647240b157580e5eca8a041b314db494f4230506eaae4d1240ac30f0d7af608c64645d16938acf0126a93b6dce039694128c7b3d1acaac3e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
